Repository fictadvisor/fictadvisor-bot, pull requests merged in 2023-10, with the labels that each got.

#91 bugfix #90: Fix tomorrow command
  app/bot/handlers/schedule/today.py
  app/bot/handlers/schedule/tomorrow.py
  app/messages/events.py
  app/utils/date_service.py
Labels: bugfix

#92 feature #89: Add bind and enable commands
  app/bot/filters/is_captain_or_deputy.py
  app/bot/handlers/group/__init__.py
  app/bot/handlers/group/bind.py
  app/bot/handlers/group/enable.py
  app/schedule.py
  app/services/telegram_group_api.py
  app/services/types/teleram_group.py
Labels: feature

#94 feature #93: Add fortnight command
  app/bot/handlers/schedule/__init__.py
  app/bot/handlers/schedule/fortnight.py
  app/bot/keyboards/types/select_week.py
  app/bot/keyboards/week_keyboard.py
  app/messages/events.py
  app/schedule.py
Labels: feature

#96 enhancement #95: Add return user to filter IsCaptainOrDeputy
  app/bot/filters/is_captain_or_deputy.py
  app/bot/handlers/group/__init__.py
  app/bot/handlers/group/bind.py
  app/bot/handlers/group/captain_button_press_callback.py
  app/bot/handlers/group/enable.py
  app/services/types/telegram_groups.py
Labels: enhancement

#97 Added description for commands
  app/bot/factory.py
  app/utils/commands.py
Labels: enhancement

#100 refactoring #98: Change discipline type names to stickers
  app/bot/handlers/schedule/today.py
  app/messages/events.py
  app/utils/get_discipline_type_name.py
Labels: refactoring

#101 refactoring #99: Move link for event to title
  app/bot/handlers/schedule/fortnight.py
  app/bot/handlers/schedule/today.py
  app/bot/handlers/schedule/tomorrow.py
  app/bot/handlers/schedule/week.py
  app/messages/events.py
Labels: refactoring
